
#include <iostream>
#include <vector>
#include <string>
#include "gllm.h"

#ifdef USE_OPENCL
    // Source files - Paths relative to this header file's location
    std::vector<std::string> kernelSourceFiles = {
        "d:/gLLM/src/maths/src/basic/cl/activations.cl",
        "d:/gLLM/src/maths/src/basic/cl/vect.cl",
        "d:/gLLM/src/maths/src/mat/cl/operators.cl",
        "d:/gLLM/src/neural/src/mlp/cl/mlp.cl",
        "d:/gLLM/src/neural/src/attention/cl/attention.cl",
        "d:/gLLM/src/model/src/tokens/token.cl"
    };

    // Kernel names - Must be unique across ALL source files loaded into the context
    std::vector<std::string> kernelNames = {
        // vect.cl
        "matrixMultiplyKernel",
        "vectorAddKernel",
        "vectorsAddKernel",
        // operators.cl
        "matrix_transpose",
        "matrix_multiply",
        "vector_matrix_multiply",
        "dot_matrix_vector",
        "vectorxMatTkernel",
        "matxMatTkernel",
        "dot_vector_matrix_vector",
        // activations.cl
        "clSigmoid",
        "clSigmoid1d",
        "clSigmoid2d",
        "clSigmoidder",
        "clSigmoid1dder",
        "clSigmoid2dder",
        "clSoftmax1d",
        "clSoftmax2d",
        "clSoftmax1dder",
        "clSoftmax2dder",
        "clSoftmaxd1dder_from_s",
        "clSoftmaxd2dder_from_s",
        "clReLU",
        "clReLU1d",
        "clReLU2d",
        "clReLUder",
        "clReLUder2d",
        "clLOTA1d",
        "clLOTA2d",
        "clLOTA2dmasking",
        "clLOTA1dder",
        "clLOTA2dder",
        "clLOTA2ddermasking",
        // mlp.cl
        "kernelOutputDelta",
        "l1PenaltyKernel",
        "l2PenaltyKernel",
        "absDiffKernel",
        "squaredDiffKernel",
        "kernelComputeGradMLPInput",
        "kernelOutputDeltaSigmoid",
        "kernelHiddenDeltaSigmoid",
        "kernelLastLayerDeltaSigmoid",
        "kernelUpdateWeights",
        "kernelUpdateWeightsAndGradients",
        "kernelUpdateWeightsL1",
        "kernelUpdateWeightsL2",
        "kernelUpdateInputMLP",
        "kernelLayerForward",
        "kernelMseReduction",
        "kernelRpropUpdate",
        "kernelUpdateElasticNet",
        // attention.cl
        "vectorAddKernel_attention",
        "kernelComputeKorQ",
        "kernelDotvecmatvec",
        "kernelComputePrediction",
        "kernelElementwiseMultiply",
        "kernelKdotQforSelf_train",
        "kernelKdotQforCross_train",
        "kernelKdotQ_Block1_Self_Inference",
        "kernelKdotQ_Block1_Cross_Inference",
        "kernelKdotQ_BlockN_Self_Inference",
        "kernelKdotQ_BlockN_Cross_Inference",
        "computeHeadSumsMaskedKernel",
        "accumulateWeightedVectorsKernel",
        "kernelComputeGradientsEH",
        "kernelComputeGradientsEH_EV",
        "kernelComputeGradientsEV_V",
        "kernelComputeGradDhDv",
        "kernelComputeGradDhDv_1stHead",
        "kernelComputePreMH_MV",
        "kernelComputeGradMH_MV",
        "kernelComputeGradHead",
        "kernelComputeGradKdotQ_LOTA",
        "kernelComputeGradK_Q",
        "kernelComputeGradMK_MQ",
        "kernelUpdateWeights_EH_EV",
        "kernelComputeGradDv_V",
        "kernelComputePreMV_V",
        "kernelComputeGradMV_V",
        "kernelComputeGradHead_V",
        "kernelComputeGradQ_V",
        "kernelComputeGradMQ_V",
        "kernelComputeGradMKCorrection",
        "kernelUpdateWeights_EV_V",
        "kernelComputeSimpleLOTAder",
        "kernelRowSum",
        "kernelComputeGradMK_MQ_Simplified",
        "kernelUpdateWeights_1stHead_H",
        "kernelUpdateWeights_1stHead_V",
        "kernelUpdateWeights_1stHead_HV",
        "kernelUpdateSimple",
        "accumulateEVRowsKernelCL",
        "updateEVRowsKernelCL",
        "kernelCompute_single_kq_vector",
        // model
        "generate_embeddings",
        "batchedVectorInverseKernel"
    };
#endif
