
#include "include/attention.hpp"

/**
 * @brief run attention for model operation
 * @param tokenEmbed token embeddings from input and output generated by blocks
 * @param qkCache QK' cache for KdotQ calculation (QK' = MQ x MK')
 * @param qvCache QV' cache for vertical retention vectors (QV' = MQ x MV')
 * @param khCache KH' cache for horizontal retention vectors (QH' = MQ x MH')
 * @param tokenCount number of tokens in context window for current head
 * @param blockCount current block in full context
 */
void attention::runAttention(std::vector<std::vector<float>>& tokenEmbed, mat& qkCache, mat& qvCache, mat& khCache, int& tokenCount,
    int& blockCount)
{
    //
}
